const placesData = [
   {
      id: 1,
      place: "poznan",
      location: "Wielkopolskie",
      image: ["/Polind/images/city_01.jpg", "/Polind/images/poznan1.jpg", "/Polind/images/poznan2.jpg"],
      description: ["Private walking tour in Poznan led by licensed guide", " Sightseeing only top attractions of Poznan with incredible legends", "Tickets to entry Weapon Museum in Citadel Park (in 5-hours version)", "Pick up from the hotel (only hotels in Poznan Old Town) ", "Tour program adapted to the preferences of the group", "Tips about local restaurants, patisserie, pubs"],
      duration: "2-5 hours",
      priceForAdult: 55,
      priceForKids: 15,
      priceForStudents: 25,
      guide: "Peter Marcovich",
      details: ["Confirmation will be received at time of booking ", "Wheelchair accessible ", "Stroller accessible", "Near public transportation ", "Infants must sit on laps ", "Transportation is wheelchair accessible", "Surfaces are wheelchair accessible", "Most travelers can participate", "This is a private tour / activity.Only your group will participate"]
   },
   {
      id: 2,
      place: "warsaw",
      location: "Mazowieckie",
      image: ["/Polind/images/city_02.jpg", "/Polind/images/warsaw1.jpg", "/Polind/images/warsaw2.jpg",],
      description: ["Private walking tour in Warsaw led by licensed guide", "Tour program adapted to the preferences of the group", "Tips about local restaurants, patisserie, pubs"],
      duration: "3-4 hours",
      priceForAdult: 65,
      priceForKids: 35,
      priceForStudents: 40,
      guide: "Anna Tychen",
      details: ["Confirmation will be received at time of booking", " Wheelchair accessible ", "Stroller accessible", "Near public transportation ", "Infants must sit on laps ", "Transportation is wheelchair accessible", "Surfaces are wheelchair accessible", "Most travelers can participate", "This is a private tour / activity.Only your group will participate"]

   },
   {
      id: 3,
      place: "zakopane",
      location: "Malopolskie",
      image: ["/Polind/images/city_03.jpg", "/Polind/images/zakop1.jpg", "/Polind/images/zakop2.jpg"],
      description: ["Private walking tour in Zakopane led by licensed guide", "Tour program adapted to the preferences of the group", "Tips about local restaurants, patisserie, pubs"],
      duration: "2-3 hours",
      priceForAdult: 35,
      priceForKids: 10,
      priceForStudents: 17,
      guide: "Anna Tychen",
      details: ["Confirmation will be received at time of booking", " Wheelchair accessible ", "Stroller accessible", "Near public transportation ", "Infants must sit on laps ", "Transportation is wheelchair accessible", "Surfaces are wheelchair accessible", "Most travelers can participate", "This is a private tour / activity.Only your group will participate"]

   },
   {
      id: 4,
      place: "wroclaw",
      location: "Dolnoslaskie",
      image: ["/Polind/images/city_06.jpg", "/Polind/images/wroclaw1.jpg", "/Polind/images/wroclaw2.jpg"],
      description: ["Private walking tour in Wroclow led by licensed guide", "Tour program adapted to the preferences of the group", "Tips about local restaurants, patisserie, pubs"],
      duration: "2-5 hours",
      priceForAdult: 46,
      priceForKids: 25,
      priceForStudents: 25,
      guide: "Like Yardovit",
      details: ["Confirmation will be received at time of booking ", "Wheelchair accessible ", "Stroller accessible", "Near public transportation ", "Infants must sit on laps ", "Transportation is wheelchair accessible", "Surfaces are wheelchair accessible", "Most travelers can participate", "This is a private tour / activity.Only your group will participate"]

   },
   {
      id: 5,
      place: "carpacz",
      location: "Dolnoslaskie",
      image: ["/Polind/images/place_04.jpg", "/Polind/images/carpacz1.jpeg", "/Polind/images/carpacz2.jpg"],
      description: ["Private walking tour in Carpacs led by licensed guide", "Tour program adapted to the preferences of the group", "Tips about local restaurants, patisserie, pubs"],
      duration: "4-6 hours",
      priceForAdult: 60,
      priceForKids: 35,
      priceForStudents: 35,
      guide: "Peter Marcovich",
      details: ["Confirmation will be received at time of booking ", "Wheelchair accessible ", "Stroller accessible", "Near public transportation ", "Infants must sit on laps ", "Transportation is wheelchair accessible", "Surfaces are wheelchair accessible", "Most travelers can participate", "This is a private tour / activity.Only your group will participate"]
   },
   {
      id: 6,
      place: "sandomierz",
      location: "Swietokrzyskie",
      image: ["/Polind/images/santomierz.jpg", "/Polind/images/sandomierz1.jpg", "/Polind/images/sandomierz2.jpg"],
      description: ["Private walking tour in Sandomierz led by licensed guide", "Tour program adapted to the preferences of the group", "Tips about local restaurants, patisserie, pubs"],
      duration: "2-3 hours",
      priceForAdult: 30,
      priceForKids: 10,
      priceForStudents: 15,
      guide: "Like Yardovit",
      details: ["Confirmation will be received at time of booking ", "Wheelchair accessible ", "Stroller accessible", "Near public transportation ", "Infants must sit on laps ", "Transportation is wheelchair accessible", "Surfaces are wheelchair accessible", "Most travelers can participate", "This is a private tour / activity.Only your group will participate"]
   },
   {
      id: 7,
      place: "dolina Olczyska",
      location: "Malopolskie",
      image: ["/Polind/images/dolyna1.jpg", "/Polind/images/dolyna2.jpg", "/Polind/images/dolyna3.jpg"],
      description: ["Private walking tour in Dolina Olczyska led by licensed guide", "Tour program adapted to the preferences of the group", "Tips about local restaurants, patisserie, pubs"],
      duration: "2-3 hours",
      priceForAdult: 55,
      priceForKids: 25,
      priceForStudents: 20,
      guide: "Peter Marcovich",
      details: ["Confirmation will be received at time of booking", " Wheelchair accessible ", "Stroller accessible", "Near public transportation ", "Infants must sit on laps ", "Transportation is wheelchair accessible", "Surfaces are wheelchair accessible", "Most travelers can participate", "This is a private tour / activity.Only your group will participate"]
   },
   {
      id: 8,
      place: "kozy",
      location: "Slaskie",
      image: ["/Polind/images/kozy1.jpg", "/Polind/images/kozy2.jpg", "/Polind/images/kozy3.jpg"],
      description: ["Private walking tour in Kozy led by licensed guide", "Tour program adapted to the preferences of the group", "Tips about local restaurants, patisserie, pubs"],
      duration: "2 hours",
      priceForAdult: 40,
      priceForKids: 15,
      priceForStudents: 18,
      guide: "Odra Mekatch",
      details: ["Confirmation will be received at time of booking", " Wheelchair accessible ", "Stroller accessible", "Near public transportation ", "Infants must sit on laps ", "Transportation is wheelchair accessible", "Surfaces are wheelchair accessible", "Most travelers can participate", "This is a private tour / activity.Only your group will participate"]
   },
   {
      id: 9,
      place: "krakiv",
      location: "Krakiv",
      image: ["/Polind/images/city_04.jpg", "/Polind/images/krakow1.jpg", "/Polind/images/krakow2.jpg"],
      description: ["Private walking tour in Krakiv led by licensed guide", "Tour program adapted to the preferences of the group", "Tips about local restaurants, patisserie, pubs"],
      duration: "4 hours",
      priceForAdult: 50,
      priceForKids: 28,
      priceForStudents: 28,
      guide: "Peter Marcovich",
      details: ["Confirmation will be received at time of booking ", "Wheelchair accessible ", "Stroller accessible", "Near public transportation ", "Infants must sit on laps ", "Transportation is wheelchair accessible", "Surfaces are wheelchair accessible", "Most travelers can participate", "This is a private tour / activity.Only your group will participate"]
   },
   {
      id: 10,
      place: "torun",
      location: "Torun",
      image: ["/Polind/images/city_05.jpg", "/Polind/images/torun1.jpg", "/Polind/images/torun2.jpg"],
      description: ["Private walking tour in Torun led by licensed guide", " Sightseeing only top attractions of Torun with incredible legends", "Tour program adapted to the preferences of the group", "Tips about local restaurants, patisserie, pubs"],
      duration: "3 hours",
      priceForAdult: 65,
      priceForKids: 35,
      priceForStudents: 35,
      guide: "Odra Mekatch",
      details: ["Confirmation will be received at time of booking", " Wheelchair accessible ", "Stroller accessible", "Near public transportation ", "Infants must sit on laps ", "Transportation is wheelchair accessible", "Surfaces are wheelchair accessible", "Most travelers can participate", "This is a private tour / activity.Only your group will participate"]
   },
   {
      id: 11,
      place: "sopot",
      location: "Pomorskie",
      image: ["/Polind/images/sopot1.jpg", "/Polind/images/sopot2.jpg", "/Polind/images/sopot3.jpg"],
      description: ["Private walking tour in Sopot led by licensed guide", " Sightseeing only top attractions  with incredible legends", "Tickets to entry  Museum in Citadel Park (in 5-hours version)", "Pick up from the hotel (only hotels in Sopot Old Town) ", "Tour program adapted to the preferences of the group", "Tips about local restaurants, patisserie, pubs"],
      duration: "3 hours",
      priceForAdult: 75,
      priceForKids: 45,
      priceForStudents: 35,
      guide: "Like Yardovit",
      details: ["Confirmation will be received at time of booking ", "Wheelchair accessible ", "Stroller accessible", "Near public transportation ", "Infants must sit on laps ", "Transportation is wheelchair accessible", "Surfaces are wheelchair accessible", "Most travelers can participate", "This is a private tour / activity.Only your group will participate"]
   },
];